"use client";
import FormField from "@/components/FormField";
import preview from "@/public/assets/preview.png";
import React, { useState } from "react";
import Image from "next/image";
import Loader from "../loader";

const page = () => {
  const [form, setForm] = useState({
    name: "",
    prompt: "",
    photo: "",
  });
  const [generatingImg, setGeneratingImg] = useState(false);
  const handleSubmit = () => {};
  const handleChange = () => {};
  const handleSurpriseMe = () => {};
  return (
    <section className="max-w-7xl  mx-auto flex flex-col gap-4 p-4">
      <div>
        <h1 className="text-xl font-bold text-black">Create</h1>
        <p className="text-sm font-semibold text-gray-500">
          Create imaginative and visually stunning images generated by DALL-E AI
          and share them with the community
        </p>
      </div>
      <form onSubmit={handleSubmit} className="mt-16 max-w-3xl">
        <div className="flex flex-col gap-5">
          <FormField
            name="name"
            placeholder="Jhon Doe"
            onChange={handleChange}
            value={form.name}
            labelName="Your Name"
            type="text"
          />
          <FormField
            labelName="Your Prompt"
            type="text"
            name="prompt"
            placeholder="teddy bears shopping for groceries in Japan, ukiyo-e"
            onChange={handleChange}
            value={form.prompt}
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
          />
          <div
            className="relative
      border border-gray-500 bg-gray-200  focus:border-blue-600 text-gray-950  outline-none p-4 my-4 rounded-lg  w-64 h-64 flex justify-center items-center
      "
          >
            {form.photo ? (
              <Image
                src={form.photo}
                alt={form.prompt}
                className="w-full h-full object-contain"
                loader={generatingImg && <Loader />}
              />
            ) : (
              <Image
                src={preview}
                alt="preview"
                className="w-9/12 h-9/12 object-contain opacity-40"
              />
            )}
            {/* //use loader from next  */}
            {generatingImg && (
              <div className="absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg">
                <Loader />
              </div>
            )}
          </div>
        </div>
      </form>
    </section>
  );
};

export default page;
